### ISSUE TITLE
Please add subscribing to mqtt messages

### ISSUE THREAD

**Issue by jbachelor** [aws-samples/aws-iot-core-http-sigv4-dotnet-app#1]
I am very happy and grateful for this code sample. Thank you so much! My team and I are writing a Xamarin.Forms app which is meant to connect to remote hardware devices using the AWS IoT Core MQTT broker, and what would make this sample truly awesome is if you provided information and sample code on not just publishing, but also how we can subscribe to messages coming back from the remote device. Without this, we are dead in the water, as we need this return data to populate the UI of the app. Please consider adding this crucial functionality to this (or another) code sample.

**Comment by sundarnarasiman** [comment]
With plain HTTP, it does not support subscription of messages. If you need support for Subscription, look at options with Mqtt Protocol. Please refer the below.

AWS IOT device publiser and consumer using .NET framework and .NET core
https://github.com/aws-samples/iot-dotnet-publisher-consumer
 
AWS IoT Core Dotnet app Mqtt over Web Sockets
 
https://github.com/aws-samples/aws-iot-core-dotnet-app-mqtt-over-websockets-sigv4
